### ISSUE TITLE
Tipos

### ISSUE THREAD

**Issue by FabioVCoelho** [gabrielmuller/bd1#1]
Acho que não é necessário criar uma tabela para os tipos/indicador, tendo um atributo em Solicitação com esses tipos e o indicador já é suficiente.

Quanto à Hipotese... Acho que tá invertido a relação... Uma solicitação pode ter 4 Hipoteses e uma hipotese pode um não ter uma solicitação.

**Comment by gabrielmuller** [comment]
Eu vi nesse documento http://www.eln.gov.br/opencms/export/sites/eletronorte/aEmpresa/saudePPRS/tiss/Manual_TISS_2_1_03.pdf lá pela página 50 que os tipos têm alguns possíveis valores, cada um com um significado. Esqueci de colocar um atributo descrição nas tabelas. Também poderia ser só um atributo em solicitação.

Não entendi como uma hipótese poderia não ter uma solicitação

**Comment by FabioVCoelho** [comment]
Uowwww, isso sim é um documento importante ^^

Segundo o manual, como não é obrigatório seria algo assim:
Solicitacao (0,n) Hipoteses(CID10)
Hipoteses(CID10) (0,n) Solicitacoes

**Comment by gabrielmuller** [comment]
O diagnóstico principal é obrigatório, os outros são opcionais, então o de baixo deve ser (1,n). Agora vi que o CID10 é um código padronizado de doenças, então faz sentido o de cima ser (0,n).

**Comment by FabioVCoelho** [comment]
Ok, colocar os atributos nos tipos, mudar o relacionamento de Solicitacao/Hipotese.
