### ISSUE TITLE
Conselho/Solicitante

### ISSUE THREAD

**Issue by FabioVCoelho** [gabrielmuller/bd1#2]
A relação Solicitante/Conselho tem uma chave primaria que não sei aonde vai =x

**Comment by gabrielmuller** [comment]
Esqueci desse. Acho que vai no solicitante, junto com a FK do conselho.

**Comment by FabioVCoelho** [comment]
A especialização do solicitante seria total ou parcial?
Se for parcial Solicitante precisa de uma PK
Senão tá ok.
